Repository hyochan/flutter_calendar_carousel, pull requests merged in 2018-12, with the labels that each got.

#23 Better localization support
  lib/flutter_calendar_carousel.dart
Labels: enhancement, feature

#36 EventList bug fixing
  example/lib/main.dart
  lib/classes/event.dart
  lib/classes/event_list.dart
Labels: bugfix

#43 Fix weekend days text style
  example/pubspec.lock
  lib/flutter_calendar_carousel.dart
Labels: bugfix, enhancement

#44 headerTitleTouchable and onHeaderTitlePressed props added
  lib/flutter_calendar_carousel.dart
Labels: enhancement, feature
