Repository hyochan/flutter_calendar_carousel, pull requests merged in 2019-11, with the labels that each got.

#172 add custom month range #161
  lib/flutter_calendar_carousel.dart
Labels: enhancement

#174 enhace: Expose `scrollPhysics` for page builder
  CHANGELOG.md
  README.md
  example/pubspec.lock
  lib/flutter_calendar_carousel.dart
  pubspec.yaml
Labels: enhancement, release

#176 fix header_arrow button onPressed
  lib/flutter_calendar_carousel.dart
Labels: bugfix

#183 Target date for custom header
  example/lib/main.dart
  lib/flutter_calendar_carousel.dart
Labels: feature
