Repository hyochan/flutter_calendar_carousel, pull requests merged in 2019-10, with the labels that each got.

#159 release/1.3.29
  CHANGELOG.md
  example/lib/main.dart
  example/pubspec.lock
  lib/flutter_calendar_carousel.dart
  pubspec.yaml
Labels: feature, release

#160 Release/1.4.0
  CHANGELOG.md
  example/lib/main.dart
  example/pubspec.lock
  lib/flutter_calendar_carousel.dart
  pubspec.yaml
Labels: bugfix, release

#165 Fixed Week view and month view show not the same dates and days.(#123)
  lib/flutter_calendar_carousel.dart
Labels: bugfix

#166 Added option for set scrollDirection (horizontal or vertical)
  lib/flutter_calendar_carousel.dart
Labels: enhancement
