Repository hyochan/flutter_calendar_carousel, pull requests merged in 2019-02, with the labels that each got.

#68 [WIP] Refactoring - Move out default styles
  lib/flutter_calendar_carousel.dart
  lib/src/default_styles.dart
Labels: refactor

#71 Setting dot icon per event
  lib/flutter_calendar_carousel.dart
Labels: enhancement

#73 [WIP] Refactoring - Separate and Test Header
  lib/flutter_calendar_carousel.dart
  lib/src/calendar_header.dart
  test/src/header_test.dart
Labels: refactoring
