Repository hyochan/flutter_calendar_carousel, pull requests merged in 2019-09, with the labels that each got.

#143 Release/1.3.20
  CHANGELOG.md
  README.md
  example/pubspec.lock
  lib/classes/event.dart
  lib/flutter_calendar_carousel.dart
  pubspec.yaml
  test/flutter_calendar_carousel_test.dart
  test/src/header_test.dart
Labels: enhancement, release

#144 Release/1.3.23
  CHANGELOG.md
  README.md
  example/lib/main.dart
  example/pubspec.lock
  lib/classes/event.dart
  lib/flutter_calendar_carousel.dart
  lib/src/calendar_header.dart
  lib/src/weekday_row.dart
  pubspec.yaml
Labels: bugfix, feature, release

#145 Custom day container feature.
  README.md
  lib/flutter_calendar_carousel.dart
Labels: enhancement, feature

#146 Removed dependency on date_utils and upgrade intl to 0.16.0
  example/pubspec.lock
  lib/flutter_calendar_carousel.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#147 Custom day builder bug fix.
  lib/flutter_calendar_carousel.dart
Labels: bugfix

#149 Allow the use of generic type with Interface
  lib/classes/event.dart
  lib/flutter_calendar_carousel.dart
Labels: enhancement, feature

#150 Added doc to custom weekday builder. Weekday number is now supplied to the builder.
  lib/flutter_calendar_carousel.dart
  lib/src/weekday_row.dart
Labels: doc, enhancement
