Repository hyochan/flutter_calendar_carousel, pull requests merged in 2019-01, with the labels that each got.

#45 headerTitleTouchable, onHeaderTitlePressed added
  README.md
Labels: doc

#47 Ability to choose the weekday format on the constructor
  README.md
  lib/flutter_calendar_carousel.dart
Labels: feature

#62 Add property for static six week format
  README.md
  lib/flutter_calendar_carousel.dart
Labels: feature

#65 fixed issue: `selectedDayTextStyle` property is not being respects
  lib/flutter_calendar_carousel.dart
Labels: bugfix
