Repository hyochan/flutter_calendar_carousel, pull requests merged in 2020-10, with the labels that each got.

#231 Optimize the initialization of page numbers.
  example/android/gradle.properties
  example/pubspec.lock
  lib/flutter_calendar_carousel.dart
  pubspec.lock
  test/flutter_calendar_carousel_test.dart
Labels: feature

#234 Fix widget constructor
  lib/flutter_calendar_carousel.dart
Labels: enhancement

#243 [Bugfix]- When switch month error - "The method 'call' was called on null."
  lib/flutter_calendar_carousel.dart
Labels: bugfix
