Repository hyochan/flutter_calendar_carousel, pull requests merged in 2021-11, with the labels that each got.

#290 feat: Added extra fields in the Event class
  lib/classes/event.dart
Labels: enhancement

#293 Update build config on flutter V2 embedding
  example/android/app/build.gradle
  example/android/app/src/main/AndroidManifest.xml
  example/android/app/src/main/java/com/dooboolab/example/MainActivity.java
  example/android/build.gradle
  example/android/gradle.properties
  example/android/gradle/wrapper/gradle-wrapper.properties
  example/ios/Flutter/AppFrameworkInfo.plist
  example/ios/Runner.xcodeproj/project.pbxproj
  pubspec.lock
  pubspec.yaml
Labels: release, build

#294 Include github workflow
  .github/workflows/ci.yml
  README.md
  lib/classes/marked_date.dart
  lib/classes/multiple_marked_dates.dart
  lib/flutter_calendar_carousel.dart
Labels: ci
